### ISSUE TITLE
add persons as publisher/creator

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/requirements-datasets#74] opened 2022-10-11 13:34 UTC
Now only possibility to specify an organization.
Person must have URI (like ORCID)?
Look at GDRP implications (when the Dataset register copies and stores person information, do we need to have privacy policy?)
Request from ATM.

**Comment by ddeboer** [comment] 2022-11-03 10:27
Duplicate of #53, itself a duplicate of #37?

**Comment by coret** [comment] 2022-11-03 17:41
Indeed, long standing issue resulting in duplicates.

Current status: the CISO of the maintainer of the Dataset Register has been asked to see if we don't run into GDPR issues when processing `schema:Person`.

**Comment by ddeboer** [comment] 2022-11-03 20:06
Let’s continue in #37, the original issue.

**Comment by coret** [comment] 2023-01-16 10:11
Legal has reviewed the fact that dataset descriptions could include personal information and has determined (the requirements under which) the Dataset Register can process this data. We can therefor add schema:Person as a valid class for schema:creator and schema:publisher (and also introduce schema:contactPoint - [issue 55](https://github.com/netwerk-digitaal-erfgoed/requirements-datasets/issues/55)). 

After the req's have been ammended, the Dataset Register component should reflect the changes (read: be able to validate and convert) as does the demonstrator.

**Closed** 2023-01-24 11:47 UTC
